import { FC, ReactNode } from 'react'
import Head from 'next/head'
import { withModal } from '@/context/modal'

type AppLayoutProps = {
  children: ReactNode
}

const AppLayout: FC<AppLayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Mason Mint</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {children}
    </>
  )
}

export default withModal(AppLayout)
